// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	CommentVotes  string
	Comments      string
	Notifications string
	Photos        string
	PostPhotos    string
	PostVotes     string
	Posts         string
	SavedPosts    string
	UserDevices   string
	UserSeenPosts string
	Users         string
}{
	CommentVotes:  "comment_votes",
	Comments:      "comments",
	Notifications: "notifications",
	Photos:        "photos",
	PostPhotos:    "post_photos",
	PostVotes:     "post_votes",
	Posts:         "posts",
	SavedPosts:    "saved_posts",
	UserDevices:   "user_devices",
	UserSeenPosts: "user_seen_posts",
	Users:         "users",
}
