// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SavedPost is an object representing the database table.
type SavedPost struct {
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PostID    string    `boil:"post_id" json:"post_id" toml:"post_id" yaml:"post_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *savedPostR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L savedPostL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SavedPostColumns = struct {
	UserID    string
	PostID    string
	CreatedAt string
}{
	UserID:    "user_id",
	PostID:    "post_id",
	CreatedAt: "created_at",
}

var SavedPostTableColumns = struct {
	UserID    string
	PostID    string
	CreatedAt string
}{
	UserID:    "saved_posts.user_id",
	PostID:    "saved_posts.post_id",
	CreatedAt: "saved_posts.created_at",
}

// Generated where

var SavedPostWhere = struct {
	UserID    whereHelperstring
	PostID    whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	UserID:    whereHelperstring{field: "\"saved_posts\".\"user_id\""},
	PostID:    whereHelperstring{field: "\"saved_posts\".\"post_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"saved_posts\".\"created_at\""},
}

// SavedPostRels is where relationship names are stored.
var SavedPostRels = struct {
	Post string
}{
	Post: "Post",
}

// savedPostR is where relationships are stored.
type savedPostR struct {
	Post *Post `boil:"Post" json:"Post" toml:"Post" yaml:"Post"`
}

// NewStruct creates a new relationship struct
func (*savedPostR) NewStruct() *savedPostR {
	return &savedPostR{}
}

func (o *SavedPost) GetPost() *Post {
	if o == nil {
		return nil
	}

	return o.R.GetPost()
}

func (r *savedPostR) GetPost() *Post {
	if r == nil {
		return nil
	}

	return r.Post
}

// savedPostL is where Load methods for each relationship are stored.
type savedPostL struct{}

var (
	savedPostAllColumns            = []string{"user_id", "post_id", "created_at"}
	savedPostColumnsWithoutDefault = []string{"user_id", "post_id"}
	savedPostColumnsWithDefault    = []string{"created_at"}
	savedPostPrimaryKeyColumns     = []string{"user_id", "post_id"}
	savedPostGeneratedColumns      = []string{}
)

type (
	// SavedPostSlice is an alias for a slice of pointers to SavedPost.
	// This should almost always be used instead of []SavedPost.
	SavedPostSlice []*SavedPost
	// SavedPostHook is the signature for custom SavedPost hook methods
	SavedPostHook func(context.Context, boil.ContextExecutor, *SavedPost) error

	savedPostQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	savedPostType                 = reflect.TypeOf(&SavedPost{})
	savedPostMapping              = queries.MakeStructMapping(savedPostType)
	savedPostPrimaryKeyMapping, _ = queries.BindMapping(savedPostType, savedPostMapping, savedPostPrimaryKeyColumns)
	savedPostInsertCacheMut       sync.RWMutex
	savedPostInsertCache          = make(map[string]insertCache)
	savedPostUpdateCacheMut       sync.RWMutex
	savedPostUpdateCache          = make(map[string]updateCache)
	savedPostUpsertCacheMut       sync.RWMutex
	savedPostUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var savedPostAfterSelectMu sync.Mutex
var savedPostAfterSelectHooks []SavedPostHook

var savedPostBeforeInsertMu sync.Mutex
var savedPostBeforeInsertHooks []SavedPostHook
var savedPostAfterInsertMu sync.Mutex
var savedPostAfterInsertHooks []SavedPostHook

var savedPostBeforeUpdateMu sync.Mutex
var savedPostBeforeUpdateHooks []SavedPostHook
var savedPostAfterUpdateMu sync.Mutex
var savedPostAfterUpdateHooks []SavedPostHook

var savedPostBeforeDeleteMu sync.Mutex
var savedPostBeforeDeleteHooks []SavedPostHook
var savedPostAfterDeleteMu sync.Mutex
var savedPostAfterDeleteHooks []SavedPostHook

var savedPostBeforeUpsertMu sync.Mutex
var savedPostBeforeUpsertHooks []SavedPostHook
var savedPostAfterUpsertMu sync.Mutex
var savedPostAfterUpsertHooks []SavedPostHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SavedPost) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SavedPost) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SavedPost) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SavedPost) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SavedPost) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SavedPost) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SavedPost) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SavedPost) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SavedPost) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range savedPostAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSavedPostHook registers your hook function for all future operations.
func AddSavedPostHook(hookPoint boil.HookPoint, savedPostHook SavedPostHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		savedPostAfterSelectMu.Lock()
		savedPostAfterSelectHooks = append(savedPostAfterSelectHooks, savedPostHook)
		savedPostAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		savedPostBeforeInsertMu.Lock()
		savedPostBeforeInsertHooks = append(savedPostBeforeInsertHooks, savedPostHook)
		savedPostBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		savedPostAfterInsertMu.Lock()
		savedPostAfterInsertHooks = append(savedPostAfterInsertHooks, savedPostHook)
		savedPostAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		savedPostBeforeUpdateMu.Lock()
		savedPostBeforeUpdateHooks = append(savedPostBeforeUpdateHooks, savedPostHook)
		savedPostBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		savedPostAfterUpdateMu.Lock()
		savedPostAfterUpdateHooks = append(savedPostAfterUpdateHooks, savedPostHook)
		savedPostAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		savedPostBeforeDeleteMu.Lock()
		savedPostBeforeDeleteHooks = append(savedPostBeforeDeleteHooks, savedPostHook)
		savedPostBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		savedPostAfterDeleteMu.Lock()
		savedPostAfterDeleteHooks = append(savedPostAfterDeleteHooks, savedPostHook)
		savedPostAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		savedPostBeforeUpsertMu.Lock()
		savedPostBeforeUpsertHooks = append(savedPostBeforeUpsertHooks, savedPostHook)
		savedPostBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		savedPostAfterUpsertMu.Lock()
		savedPostAfterUpsertHooks = append(savedPostAfterUpsertHooks, savedPostHook)
		savedPostAfterUpsertMu.Unlock()
	}
}

// One returns a single savedPost record from the query.
func (q savedPostQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SavedPost, error) {
	o := &SavedPost{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for saved_posts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SavedPost records from the query.
func (q savedPostQuery) All(ctx context.Context, exec boil.ContextExecutor) (SavedPostSlice, error) {
	var o []*SavedPost

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to SavedPost slice")
	}

	if len(savedPostAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SavedPost records in the query.
func (q savedPostQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count saved_posts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q savedPostQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if saved_posts exists")
	}

	return count > 0, nil
}

// Post pointed to by the foreign key.
func (o *SavedPost) Post(mods ...qm.QueryMod) postQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PostID),
	}

	queryMods = append(queryMods, mods...)

	return Posts(queryMods...)
}

// LoadPost allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (savedPostL) LoadPost(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSavedPost any, mods queries.Applicator) error {
	var slice []*SavedPost
	var object *SavedPost

	if singular {
		var ok bool
		object, ok = maybeSavedPost.(*SavedPost)
		if !ok {
			object = new(SavedPost)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSavedPost)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSavedPost))
			}
		}
	} else {
		s, ok := maybeSavedPost.(*[]*SavedPost)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSavedPost)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSavedPost))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &savedPostR{}
		}
		args[object.PostID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &savedPostR{}
			}

			args[obj.PostID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`posts`),
		qm.WhereIn(`posts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Post")
	}

	var resultSlice []*Post
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Post")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for posts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
	}

	if len(postAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Post = foreign
		if foreign.R == nil {
			foreign.R = &postR{}
		}
		foreign.R.SavedPosts = append(foreign.R.SavedPosts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PostID == foreign.ID {
				local.R.Post = foreign
				if foreign.R == nil {
					foreign.R = &postR{}
				}
				foreign.R.SavedPosts = append(foreign.R.SavedPosts, local)
				break
			}
		}
	}

	return nil
}

// SetPost of the savedPost to the related item.
// Sets o.R.Post to related.
// Adds o to related.R.SavedPosts.
func (o *SavedPost) SetPost(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Post) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"saved_posts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"post_id"}),
		strmangle.WhereClause("\"", "\"", 2, savedPostPrimaryKeyColumns),
	)
	values := []any{related.ID, o.UserID, o.PostID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PostID = related.ID
	if o.R == nil {
		o.R = &savedPostR{
			Post: related,
		}
	} else {
		o.R.Post = related
	}

	if related.R == nil {
		related.R = &postR{
			SavedPosts: SavedPostSlice{o},
		}
	} else {
		related.R.SavedPosts = append(related.R.SavedPosts, o)
	}

	return nil
}

// SavedPosts retrieves all the records using an executor.
func SavedPosts(mods ...qm.QueryMod) savedPostQuery {
	mods = append(mods, qm.From("\"saved_posts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"saved_posts\".*"})
	}

	return savedPostQuery{q}
}

// FindSavedPost retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSavedPost(ctx context.Context, exec boil.ContextExecutor, userID string, postID string, selectCols ...string) (*SavedPost, error) {
	savedPostObj := &SavedPost{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"saved_posts\" where \"user_id\"=$1 AND \"post_id\"=$2", sel,
	)

	q := queries.Raw(query, userID, postID)

	err := q.Bind(ctx, exec, savedPostObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from saved_posts")
	}

	if err = savedPostObj.doAfterSelectHooks(ctx, exec); err != nil {
		return savedPostObj, err
	}

	return savedPostObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SavedPost) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no saved_posts provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(savedPostColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	savedPostInsertCacheMut.RLock()
	cache, cached := savedPostInsertCache[key]
	savedPostInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			savedPostAllColumns,
			savedPostColumnsWithDefault,
			savedPostColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(savedPostType, savedPostMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(savedPostType, savedPostMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"saved_posts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"saved_posts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into saved_posts")
	}

	if !cached {
		savedPostInsertCacheMut.Lock()
		savedPostInsertCache[key] = cache
		savedPostInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SavedPost.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SavedPost) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	savedPostUpdateCacheMut.RLock()
	cache, cached := savedPostUpdateCache[key]
	savedPostUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			savedPostAllColumns,
			savedPostPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update saved_posts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"saved_posts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, savedPostPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(savedPostType, savedPostMapping, append(wl, savedPostPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update saved_posts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for saved_posts")
	}

	if !cached {
		savedPostUpdateCacheMut.Lock()
		savedPostUpdateCache[key] = cache
		savedPostUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q savedPostQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for saved_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for saved_posts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SavedPostSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), savedPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"saved_posts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, savedPostPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in savedPost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all savedPost")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SavedPost) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no saved_posts provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(savedPostColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	savedPostUpsertCacheMut.RLock()
	cache, cached := savedPostUpsertCache[key]
	savedPostUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			savedPostAllColumns,
			savedPostColumnsWithDefault,
			savedPostColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			savedPostAllColumns,
			savedPostPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert saved_posts, could not build update column list")
		}

		ret := strmangle.SetComplement(savedPostAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(savedPostPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert saved_posts, could not build conflict column list")
			}

			conflict = make([]string, len(savedPostPrimaryKeyColumns))
			copy(conflict, savedPostPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"saved_posts\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(savedPostType, savedPostMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(savedPostType, savedPostMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert saved_posts")
	}

	if !cached {
		savedPostUpsertCacheMut.Lock()
		savedPostUpsertCache[key] = cache
		savedPostUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SavedPost record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SavedPost) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no SavedPost provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), savedPostPrimaryKeyMapping)
	sql := "DELETE FROM \"saved_posts\" WHERE \"user_id\"=$1 AND \"post_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from saved_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for saved_posts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q savedPostQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no savedPostQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from saved_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for saved_posts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SavedPostSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(savedPostBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), savedPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"saved_posts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, savedPostPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from savedPost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for saved_posts")
	}

	if len(savedPostAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SavedPost) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSavedPost(ctx, exec, o.UserID, o.PostID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SavedPostSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SavedPostSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), savedPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"saved_posts\".* FROM \"saved_posts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, savedPostPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in SavedPostSlice")
	}

	*o = slice

	return nil
}

// SavedPostExists checks if the SavedPost row exists.
func SavedPostExists(ctx context.Context, exec boil.ContextExecutor, userID string, postID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"saved_posts\" where \"user_id\"=$1 AND \"post_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, postID)
	}
	row := exec.QueryRowContext(ctx, sql, userID, postID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if saved_posts exists")
	}

	return exists, nil
}

// Exists checks if the SavedPost row exists.
func (o *SavedPost) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SavedPostExists(ctx, exec, o.UserID, o.PostID)
}
